### ISSUE TITLE
Unix builds are broken

### ISSUE THREAD

**Issue by danfe** [Serg-Norseman/GKCommunicator#2]
Commit eb5f45a changed one include reference from `"System"` to `"System.XML"` in _GKNetCore/GKNetCore.csproj_ file which causes a build failure on Unix-like systems:
```
error CS0234: The type or namespace name 'Xml' does not exist in the namespace 'System' (are you missing an assembly reference?)
```
Correct spelling is `"System.Xml"`.  I guess it went unnoticed on Windows due to case-insensitivity.

**Comment by Serg-Norseman** [comment]
Both ways are compiled on Ubuntu: both System.Xml and System.XML. Like on Windows.

Specify, on FreeBSD only "System.Xml" is compiled?

**Comment by danfe** [comment]
> Both ways are compiled on Ubuntu: both System.Xml and System.XML. Like on Windows.

Hmm, interesting!  What's version of Mono/.Net being used on Ubuntu?

> Specify, on FreeBSD only "System.Xml" is compiled?

Yes, I needed this change for FreeBSD port of GEDKeeper (against mono-5.10.1.57, msbuild-15.8).

**Comment by Serg-Norseman** [comment]
Linux Mint, 
Mono 6.8.0.105
XBuild 14

**Comment by Serg-Norseman** [comment]
5a2dbc31ffaaa7b5548bccfb9dbcd5767b01129e

**Comment by Serg-Norseman** [comment]
Is there a result? Builds?

**Comment by danfe** [comment]
> Mono 6.8.0.105

Perhaps they've changed something regarding case sensitivity between Mono 5.10 and 6.8.

> 5a2dbc3

Thank you!  I can now remove my local hack upon the next update.
